### ISSUE TITLE
A issue on baseline performance

### ISSUE THREAD

**Issue by 666-will** [LMZZML/PriSTI#2]
Baseline CSDI achieved better results than GRIN, but I also find CSDI may not achieve such results like in your paper.Could you publicize the experimence of CSDI?

**Comment by LMZZML** [comment]
For the experiment of CSDI, you can directly refer to the code link given in their paper. The experiments on the air quality dataset AQI-36 is completely consistent with CSDI's source code. For the two traffic datasets, you can refer to dataset_metrla.py and dataset_pemsbay.py in our code, and replace our model with CSDI. If the results are inconsistent, it may be due to hyperparameter settings.We use the same experimental settings as in the original CSDI.

**Comment by 666-will** [comment]
Thanks for your answer, the main contribution of this work I think is applicating diffusion model into time series area (after CSDI), and many works emerged this year which demonstrate the superiority of diffusion model.
